### ISSUE TITLE
楼主能实现个通过tcp调用java server层的么

### ISSUE THREAD

**Issue by comid** [ofpay/dubbo-node-client#12]
通过jsonrpc的tcp调用java的server层，这样能节省时间

**Comment by JoeCao** [comment]
几个原因不支持
1、dubbo的虚拟化的hessian，多语言支持比较弱。
2、脚本语言对于tcp、http，效率区别不是很大。

**Comment by hufeng** [comment]
tcp方案:https://github.com/hufeng/dubbo.js
